

<definitions name="Account" targetNamespace="http://Service/" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://Service/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsp="http://www.w3.org/ns/wspolicy" xmlns:wsu="http://docs.oasisopen.org/wss/2004/01/oasis200401wsswssecurityutility1.0.xsd">


<types>


<xsd:schema>

<xsd:import schemaLocation="http://localhost:8084/KTTKServer/Account?xsd=1" namespace="http://Service/"/>

</xsd:schema>

</types>


<message name="checkLogin">

<part name="parameters" element="tns:checkLogin"/>

</message>


<message name="checkLoginResponse">

<part name="parameters" element="tns:checkLoginResponse"/>

</message>


<portType name="Account">


<operation name="checkLogin">

<input message="tns:checkLogin" wsam:Action="http://Service/Account/checkLoginRequest"/>

<output message="tns:checkLoginResponse" wsam:Action="http://Service/Account/checkLoginResponse"/>

</operation>

</portType>


<binding name="AccountPortBinding" type="tns:Account">

<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>


<operation name="checkLogin">

<soap:operation soapAction=""/>


<input>

<soap:body use="literal"/>

</input>


<output>

<soap:body use="literal"/>

</output>

</operation>

</binding>


<service name="Account">


<port name="AccountPort" binding="tns:AccountPortBinding">

<soap:address location="http://localhost:8084/KTTKServer/Account"/>

</port>

</service>

</definitions>